### ISSUE TITLE
Structure에 관한 설정

### ISSUE THREAD

**Issue by MinjiKang9** [SKKU-2016-fall-db-programming/sqlite_group6#1]
[1]Structure
      (1)mid-point PGroup 구조체에 선언
             -초기화
             -크기 변경이 에러를 일으키지 않는 것을 확인함
      (2)touchcount PgHdr1에 선언
             -자료형 u32로 생각함

**Comment by MinjiKang9** [comment]
pcache1Create 함수 부분에서 midpoint = &pGroup->lru 설정

**Comment by ljhh-0611** [comment]
처음 create할때, pGroup->pLruNext 와 pGroup->pLruPrev 둘다 pGroup 자신을 가리키고 있는듯
