### ISSUE TITLE
Page miss에 관한 설정

### ISSUE THREAD

**Issue by MinjiKang9** [SKKU-2016-fall-db-programming/sqlite_group6#2]
[2]Page miss
       (1)recycle할 수 있는 page가 있을 경우(step 4, FetchStage2)
            -recycle step 4 조건문을 들어자마자 바로, clean LRU의 tail->head로 for문 돌면서 체크
                        -touchcount>=c(c:constant): LRU의 head로 해당 페이지를 옮기고 touchcount=0로 셋팅.
                        -touchcount<c 라면 for문 빠져나와 나머지 recycle 부분을 진행한다.
                                  (주의) pcache1PinPage함수가 불릴 때, 우리의 수정코드는 해당 함수에서 
                                     아무 동작도 하지 않으므로, 원래 함수에 있던 내용을 추가한다.
       (2)step 5의 if(!pPage) 조건문 밑 if(pPage) 조건문의 statement 변경
            -clean LRU의 midpoint paged의 prev에 page 추가.
                         (수도 코드)
                              if(midpoint==&PGroup->lru){
                                   PGroup->lru.pLruPrev=PGroup->lru.pLruNext=&1page;
                                   1page->plruPrev=1page->plruNext=&pGroup->lru;
                              }else{
                                  insertpage->pLruNext=midpoint;
                                  insertpage->pLruPrev=midpoint->pLruPrev;
                                  midpoint->pLruPrev->pLruNext=&insertpage;
                                  midpoint->pLruPrev=&insertpage;
                              }
            -touchcount=1로 셋팅.
       (3)return 전에 midpoint 변경
            -반복문 돌면서 (nRecyclable/2)+1번째 page로 midpoint 변경. (lru-1-2...)
                    (pcacheFetchNoMutex함수의 while문 참조)

**Comment by ljhh-0611** [comment]
근데 마지막에 midpoint를 변경하는건 좀 cpu를 많이 잡아먹을거같고,
차라리 다음번에 한칸 앞으로 옮길지 flag를 주는 변수를 하나 더 두는게 빠르지 않을까?
예를들어, midpoint가 바뀌는건 mid-insert가 두번 일어날때마다 한번씩 앞으로 옮기는거잖아?
그때 처음 한번은 flag가 0이어서 midpoint는 옮기지 않고 대신 flag를 1로 바꾸고, 두번째 mid-insert부분에서는 flag가 1이니까 midpoint를 한칸 옮기고 flag를 0으로 만든다던지.
lru에서 page가 빠지는 부분은 그 반대로 하고!

**Comment by Taehyung0911** [comment]
근데 midpoint를 바꿔주는 경우를 두가지로 나눠보면 
1) cache에 메모리가 여유가 있어서 단순히 allocation 해주는 경우(createFlag == 1)
2) cache에 여유공간이 없어서 recycle하거나 free한 다음 allocation 해주는 경우

1)의 경우에는 밑에 코드처럼 처리해주면 하나 추가될때마다 midpoint 를 쉽게 판단하고 올릴수 있음
if(nRecyclable%2 == 1)
    midpoint = midpoint->pLruNext;

2)의 경우에는 전체 list의 크기는 일정하게 유지되기 때문에 앞 stage4 단계에서 head로 이동(countHead)하거나 victim(countVictim)이 되는 element의 갯수를 카운트. 그다음 노드를 추가하는 것을 고려해서
(countHead - countVictim - 1)/2 만큼 midpoint의 위치를 조정

이런식으로 하면 되지않늠?? 그리고 민지방법[1]에서 tail부터 head까지 전체를 스캔할 필요가 있는건가...?왜 전체를 다돌아??

**Comment by MinjiKang9** [comment]
종석이랑 그것도 알고 생각을 해봤는데, 그당시에 다른것도 정리해야 될게 많았는데 이거까지 조정하려다가 길을 잃을것같은것도 있었고, 확실한 방법으로 가고싶어서 그랬는데 만약 조정하는 방법이 확실하면 걍 그렇게 수정해도 노상관
근데 만약 nRecyclable%2==1과 같은 방식으로 하면, midpoint = midpoint->pLruNext;가 아니라 pLruPrev로 해야 함. 또한 위에서 말한 1과 2의 부분이 코드상으로는 구분되어 있는게 아니라 결국 1의 부분이 2를 거쳐가야 하므로 그 상황도 고려해줘야 할 것 같음

**Comment by J-S-Kim** [comment]
step4에서 touchcount<c 페이지를 victim으로 선정할때 pinned된 페이지인지 아닌지도 고려
