### ISSUE TITLE
Dirty 변경

### ISSUE THREAD

**Issue by MinjiKang9** [SKKU-2016-fall-db-programming/sqlite_group6#5]
[5]Dirty
            -원래 dirty 직전에 무조건 page가 Pin되어 clean lru에서 빠져나오는데,
              우리의 수정코드는 빠져나오지 않으므로, dirty 되기 전에 clean lru에서 빠져나오도록 수정해야 한다.

**Comment by ljhh-0611** [comment]
pager_write 함수에서, sqlitePcacheMakeDirty 함수를 호출하고, sqlitePcacheMakeDirty에서 pcacheManageDirtyList 함수를 호출한다.
 따라서 sqlitePcacheMakeDirty함수에서 pcacheManageDirtyList 함수를 호출하기 전, clean lru에 있는 hdr를 빼주는 작업을 추가하면 될 것이라 예상한다.
